# Generated by Django 5.2.5 on 2025-08-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_delete_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[(1, "Low"), (2, "Medium"), (3, "High")],
                default="medium",
                max_length=10,
            ),
        ),
    ]
