# Generated by Django 5.2.5 on 2025-08-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="difficulty",
            field=models.IntegerField(
                choices=[(1, "Easy"), (2, "Medium"), (3, "Difficult")], default=1
            ),
        ),
    ]
